#!/bin/bash
# ┏━┓┳  o┏┓┓┏━┓┳ ┳┳  ┏━┓┏━┓┳┏ 
# ┃ ┳┃  ┃ ┃ ┃  ┃━┫┃  ┃ ┃┃  ┣┻┓
# ┇━┛┇━┛┇ ┇ ┗━┛┇ ┻┇━┛┛━┛┗━┛┇ ┛
#
# author: xero <x@xero.nu> http://xero.nu
# requires: i3lock-color, imagemagick, scrot

scrot /tmp/lock.png
convert /tmp/lock.png /tmp/lock.jpg
file=/tmp/lock.jpg

function datamosh() {
	fileSize=$(wc -c < "$file")
	headerSize=1000
	skip=$(shuf -i "$headerSize"-"$fileSize" -n 1)
	count=$(shuf -i 1-10 -n 1)
	for i in $(seq 1 $count);do byteStr=$byteStr'\x'$(shuf -i 0-255 -n 1); done;   
	printf $byteStr | dd of="$file" bs=1 seek=$skip count=$count conv=notrunc >/dev/null 2>&1
}

steps=$(shuf -i 40-70 -n 1)
for i in $(seq 1 $steps);do datamosh "$file"; done

convert /tmp/lock.jpg /tmp/lock.png >/dev/null 2>&1
rm /tmp/lock.jpg
file=/tmp/lock.png

convert "$file" "${LOCK[@]}" "$file"

#colors
B='#00000000' # blank
C='#ffffff22' # Clear ish
D='#ff00ffcc' # default
T='#18ffffee' # text
W='#ff1744ee' # wrong

i3lock -n -i "$file" \
	--insidevercolor=$T \
	--ringvercolor=$T \
	\
	--insidewrongcolor=$W \
	--ringwrongcolor=$W \
	\
	--insidecolor=$B \
	--ringcolor=$B \
	--linecolor=$B \
	--separatorcolor=$B \
	\
	--verifcolor=$T \
	--wrongcolor=$W \
	--keyhlcolor=$T \
	--bshlcolor=$W \
	\
	--screen 1 \
	-f /dev/null 2>&1
